# use-conda: true
jobs: 10

latency-wait: 60
reason: True

keep-going: True
printshellcmds: True
rerun-incomplete: True
restart-times: 2

slurm: True
# use-conda: True
# use-singularity: False 
# conda-frontend: mamba


# conda-prefix: /dh-projects/scnsl_ffpe/analysis/software/wgs_umi_alignment_pipeline/conda_envs
# singularity-prefix: /dh-projects/scnsl_ffpe/analysis/software/wgs_umi_alignment_pipeline/Singularity
# singularity-args: "-B /dh-projects/scnsl_ffpe:/dh-projects/scnsl_ffpe,/applications/:/applications"
