# use-conda: true
jobs: 10

latency-wait: 60
reason: True

keep-going: True
printshellcmds: True
rerun-incomplete: True
restart-times: 2

conda-prefix: /dh-projects/richter_transformation/analysis/wgs_analysis/alignment_pipeline_cutadapt/conda_envs
singularity-prefix: /dh-projects/richter_transformation/analysis/wgs_analysis/alignment_pipeline_cutadapt/Singularity
singularity-args: "-B /dh-projects/richter_transformation:/dh-projects/richter_transformation,/applications/:/applications,/dh-projects/T-NHL-chapuy:/dh-projects/T-NHL-chapuy"
