# Define the default resources for SLURM jobs

# set-resources:

genome_human: /applications/otp/reference-genomes/bwa06_1KGRef_PhiX/hs37d5_PhiX.fa
dbsnp: /applications/otp/ngs_share_complete/assemblies/hg19_GRCh37_1000genomes/databases/dbSNP/dbSNP_147/00-All.vcf.gz
genotypes_snp: /home/sahays/ALL.chrALL.SNP.phase3_integrated_v5a.20130502.genotypes.vcf
genotypes_indel: /applications/otp/ngs_share_complete/assemblies/hg19_GRCh37_1000genomes/databases/1000genomes/ALL.chrALL.Indel.phase3_integrated_v5a.20130502.genotypes.vcf.gz

NEBNext-FFPE-DNA-Library-Prep-Kit_R1:
  [
    "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA",
    "AGATCGGAAGAGCACACGTCTGAAC",
    "TGGAATTCTCGGGTGCCAAGG",
    "AGATCGGAAGAGCACACGTCT",
    "CTGTCTCTTATACACATCT",
    "AGATGTGTATAAGAGACAG",
  ]

NEBNext-FFPE-DNA-Library-Prep-Kit_R3:
  [
    "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT",
    "AGATCGGAAGAGCGTCGTGTAGGGA",
    "TGGAATTCTCGGGTGCCAAGG",
    "AGATCGGAAGAGCACACGTCT",
    "CTGTCTCTTATACACATCT",
    "AGATGTGTATAAGAGACAG",
  ]

metadata: /dh-projects/richter_transformation/scratch/input_folder/bare_min_meta_data_sheet.csv

work_dir: /dh-projects/richter_transformation/scratch/output_S1

log_dir: /dh-projects/richter_transformation/scratch/output_S1/logs

sample: S1
