use-conda: true
jobs: 10

latency-wait: 60
reason: True

keep-going: True
printshellcmds: True
rerun-incomplete: True
restart-times: 3

default-resources:
  [
    "--partition=compute",
    "--exclude=eils-compute002",
    "--time=12:00:00",
    "--mem=8G",
    "--cpus-per-task=1",
  ]

configfile: /dh-projects/richter_transformation/analysis/wgs_analysis/alignment_pipeline_cutadapt/config/config/config.yaml
