Adapter_R1: []
Adapter_R3: []
SeqType: Panel
chrom_sizes: /applications/otp/reference-genomes/bwa06_1KGRef_PhiX/stats/hg19_chrTotalLength.tsv

dbsnp: /applications/otp/ngs_share_complete/assemblies/hg19_GRCh37_1000genomes/databases/dbSNP/dbSNP_147/00-All.vcf.gz
dict_genome: /applications/otp/reference-genomes/bwa06_1KGRef_PhiX/hs37d5_PhiX.dict

genome: /applications/otp/reference-genomes/bwa06_1KGRef_PhiX/hs37d5_PhiX.fa

library_prep_kit: IDT_xGen_cfDNA_FFPE

log_dir: /dh-projects/exliquid/scratch/results_alignment_test/logs/

metadata: /dh-projects/exliquid/scratch/input/bare_min_meta_data.csv

pid: EXLIQUID_EX59
sample: EXLIQUID_EX59-BUFFYCOAT_control

target_regions: /dh-projects/exliquid/raw_data/reference/Targets-XGEN.69EBBD23F90841409EAFA66D9BC58A17.g.bed
bait_regions: /dh-projects/exliquid/raw_data/reference/Probes-XGEN.69EBBD23F90841409EAFA66D9BC58A17.g.bed
# trim_adapters: false

work_dir: /dh-projects/exliquid/scratch/results_alignment_test/

# bait_regions: /Path/to/bait_regions.bed # Bed file containing the bait regions for the analysis only required if SeqType is Panel/WES, if not provided a bait file will be generated from the target file

#Parameters for Read_Grouping
group_allowed_edits: 0
group_min_mapq: 20
group_strategy: Adjacency

# Configuration for consensus calling
consensus_min_reads: 1
consensus_min_base_qual: 2
consensus_min_input_base_mapq: 10
consensus_error_rate_pre_umi: 45
consensus_error_rate_post_umi: 30

# Configuration for consensus filter
filter_min_reads: 3
filter_min_base_qual: 2
filter_max_base_error_rate: 0.1
filter_max_read_error_rate: 0.05
filter_max_no_call_fraction: 0.2

# Configuration when UMI present in R1 and R2 files
read_structure: 8M143T 8M143T
# Correct UMI based on list of UMI's
correct_umi: True
correct_umi_max_mismatches: 3
correct_umi_min_distance: 1
umi_file: /dh-projects/exliquid/raw_data/reference/umi_list.txt
